name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run unit tests
      run: |
        pytest jd_agent/tests/ -v
    
    - name: Run functional tests
      run: |
        python test/test_demo.py
        python test/test_email_collector.py
        python test/test_email_details.py
        python test/test_full_pipeline.py
        python test/test_enhanced_email_collector.py
        python test/test_enhanced_jd_parser.py
        python test/check_pipeline_results.py
    
    - name: Run additional tests
      run: |
        python test/test_embeddings_and_async_export.py
        python test/test_dedupe.py
        python test/test_structured_logging.py
        python test/test_concurrent_enhancement.py
        python test/test_prompt_engine_configurable.py
        python test/test_retry.py
        python test/test_schemas.py
        python test/test_context_compressor.py
        python test/test_prompt_engine_async.py
        python test/test_new_features.py 